"""Minimal OAuth 2.1 authorization server for the OpenMontage MCP server.

Sized for a small trusted group, not a public product — there is no
per-user account system. "Login" is a single shared password
(``MCP_SHARED_TOKEN``) shown once at ``/login``; everything downstream of
that is spec-correct OAuth 2.1 + PKCE (RFC 6749 / 7636 / 7591 / 8414 / 9728)
so both Claude Code and Claude.ai's Custom Connectors UI can drive the flow
via standard discovery. The actual ``/authorize``, ``/token``, and
``.well-known/*`` routes are generated by the SDK
(``mcp.server.auth.routes.create_auth_routes``) from this provider — see
``mcp_server/asgi.py``.

Dynamic Client Registration (RFC 7591) is enabled and is the primary path:
it's what lets Claude Code's ephemeral localhost callback port and
Claude.ai's web callback both register themselves with a ``redirect_uri`` we
can't know in advance — a single hardcoded client can't satisfy both
(``OAuthClientInformationFull.validate_redirect_uri`` requires an exact
match). A second, statically hardcoded client
(``MCP_OAUTH_CLIENT_ID``/``MCP_OAUTH_CLIENT_SECRET``) is also pre-registered
for anyone who pastes credentials into a client's manual "Advanced
settings" fields instead of going through DCR; its allowed redirect URIs
come from ``MCP_OAUTH_STATIC_REDIRECT_URIS`` (comma-separated), left empty
by default since we don't know your OAuth client's callback URL in advance —
set it once you do. Either path is gated by the same password prompt:
client_id is a routing detail here, not the security boundary.

Registered clients and issued tokens are persisted to a JSON file
(``state_path``) so a container restart/redeploy doesn't silently forget
every DCR registration a client already made — without this, each restart
forces everyone connected to remove and re-add the connector, since their
cached client_id would 404 against a server that no longer remembers it.
Pending /authorize -> /login handoffs and unredeemed authorization codes are
NOT persisted: they're short-TTL by design (a few minutes), so losing them
on restart just means retrying an in-flight login, not a real disruption.
"""

from __future__ import annotations

import asyncio
import json
import secrets
import time
from pathlib import Path
from typing import Optional

from mcp.server.auth.provider import (
    AccessToken,
    AuthorizationCode,
    AuthorizationParams,
    RefreshToken,
    construct_redirect_uri,
)
from mcp.shared.auth import OAuthClientInformationFull, OAuthToken
from pydantic import AnyUrl
from starlette.requests import Request
from starlette.responses import HTMLResponse, RedirectResponse, Response

AUTH_CODE_TTL_SECONDS = 300
ACCESS_TOKEN_TTL_SECONDS = 3600
REFRESH_TOKEN_TTL_SECONDS = 60 * 60 * 24 * 30
PENDING_TXN_TTL_SECONDS = 600


def _login_form_html(txn: str, error: Optional[str] = None) -> str:
    error_html = f'<p style="color:#c0392b">{error}</p>' if error else ""
    return f"""<!doctype html>
<html><head><title>OpenMontage — Sign in</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  body {{ font-family: system-ui, sans-serif; max-width: 380px; margin: 4rem auto; padding: 0 1rem; }}
  input {{ width: 100%; padding: 0.6rem; margin: 0.5rem 0 1rem; box-sizing: border-box; font-size: 1rem; }}
  button {{ width: 100%; padding: 0.6rem; cursor: pointer; font-size: 1rem; }}
</style></head>
<body>
  <h2>OpenMontage</h2>
  <p>Enter the shared access password to connect.</p>
  {error_html}
  <form method="post" action="/login">
    <input type="hidden" name="txn" value="{txn}">
    <label for="password">Password</label>
    <input type="password" name="password" id="password" autofocus required>
    <button type="submit">Continue</button>
  </form>
</body></html>"""


class SharedPasswordOAuthProvider:
    """Implements ``mcp.server.auth.provider.OAuthAuthorizationServerProvider``.

    All state is in-memory: a server restart invalidates every pending login,
    access token, and refresh token — acceptable for a small trusted group,
    not durable storage.
    """

    def __init__(
        self,
        *,
        shared_password: str,
        static_client_id: str,
        static_client_secret: str,
        static_redirect_uris: list[str],
        state_path: Optional[Path] = None,
    ) -> None:
        self._shared_password = shared_password
        self._clients: dict[str, OAuthClientInformationFull] = {}
        self._auth_codes: dict[str, AuthorizationCode] = {}
        self._access_tokens: dict[str, AccessToken] = {}
        self._refresh_tokens: dict[str, RefreshToken] = {}
        # authorize() -> /login handoff: txn -> (client, params, expires_at)
        self._pending: dict[str, tuple[OAuthClientInformationFull, AuthorizationParams, float]] = {}
        self._state_path = state_path
        self._lock = asyncio.Lock()

        self._load_state()

        # Always (re)built fresh from current env vars, on top of whatever
        # was loaded from disk — so rotating MCP_OAUTH_CLIENT_SECRET takes
        # effect on next restart instead of being stuck with a stale
        # persisted value.
        if static_redirect_uris:
            self._clients[static_client_id] = OAuthClientInformationFull(
                client_id=static_client_id,
                client_secret=static_client_secret,
                redirect_uris=[AnyUrl(u) for u in static_redirect_uris],
                token_endpoint_auth_method="client_secret_post",
                grant_types=["authorization_code", "refresh_token"],
                response_types=["code"],
                client_name="OpenMontage (static)",
            )

    # --- persistence ---

    def _load_state(self) -> None:
        if self._state_path is None or not self._state_path.is_file():
            return
        try:
            raw = json.loads(self._state_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return
        for client_id, data in raw.get("clients", {}).items():
            try:
                self._clients[client_id] = OAuthClientInformationFull.model_validate(data)
            except Exception:
                continue
        for token, data in raw.get("access_tokens", {}).items():
            try:
                self._access_tokens[token] = AccessToken.model_validate(data)
            except Exception:
                continue
        for token, data in raw.get("refresh_tokens", {}).items():
            try:
                self._refresh_tokens[token] = RefreshToken.model_validate(data)
            except Exception:
                continue

    def _save_state(self) -> None:
        """Caller must hold self._lock — not locked internally so mutating
        methods can batch a dict update + save under one critical section."""
        if self._state_path is None:
            return
        payload = {
            "clients": {cid: c.model_dump(mode="json") for cid, c in self._clients.items()},
            "access_tokens": {t: at.model_dump(mode="json") for t, at in self._access_tokens.items()},
            "refresh_tokens": {t: rt.model_dump(mode="json") for t, rt in self._refresh_tokens.items()},
        }
        self._state_path.parent.mkdir(parents=True, exist_ok=True)
        tmp_path = self._state_path.with_suffix(".json.tmp")
        tmp_path.write_text(json.dumps(payload), encoding="utf-8")
        tmp_path.replace(self._state_path)

    # --- OAuthAuthorizationServerProvider protocol ---

    async def get_client(self, client_id: str) -> OAuthClientInformationFull | None:
        return self._clients.get(client_id)

    async def register_client(self, client_info: OAuthClientInformationFull) -> None:
        assert client_info.client_id is not None
        async with self._lock:
            self._clients[client_info.client_id] = client_info
            self._save_state()

    async def authorize(self, client: OAuthClientInformationFull, params: AuthorizationParams) -> str:
        self._prune_pending()
        txn = secrets.token_urlsafe(24)
        self._pending[txn] = (client, params, time.time() + PENDING_TXN_TTL_SECONDS)
        return f"/login?txn={txn}"

    async def load_authorization_code(
        self, client: OAuthClientInformationFull, authorization_code: str
    ) -> AuthorizationCode | None:
        code = self._auth_codes.get(authorization_code)
        if code is None or code.client_id != client.client_id:
            return None
        if code.expires_at < time.time():
            self._auth_codes.pop(authorization_code, None)
            return None
        return code

    async def exchange_authorization_code(
        self, client: OAuthClientInformationFull, authorization_code: AuthorizationCode
    ) -> OAuthToken:
        self._auth_codes.pop(authorization_code.code, None)  # one-time use
        async with self._lock:
            token = self._mint_token(client, authorization_code.scopes, subject=authorization_code.subject)
            self._save_state()
        return token

    async def load_refresh_token(
        self, client: OAuthClientInformationFull, refresh_token: str
    ) -> RefreshToken | None:
        token = self._refresh_tokens.get(refresh_token)
        if token is None or token.client_id != client.client_id:
            return None
        if token.expires_at is not None and token.expires_at < time.time():
            self._refresh_tokens.pop(refresh_token, None)
            return None
        return token

    async def exchange_refresh_token(
        self,
        client: OAuthClientInformationFull,
        refresh_token: RefreshToken,
        scopes: list[str],
    ) -> OAuthToken:
        async with self._lock:
            self._refresh_tokens.pop(refresh_token.token, None)  # rotate on use
            for tok, at in list(self._access_tokens.items()):
                if at.client_id == client.client_id:
                    self._access_tokens.pop(tok, None)
            token = self._mint_token(client, scopes or refresh_token.scopes, subject=refresh_token.subject)
            self._save_state()
        return token

    async def load_access_token(self, token: str) -> AccessToken | None:
        return self._access_tokens.get(token)

    async def revoke_token(self, token: AccessToken | RefreshToken) -> None:
        async with self._lock:
            self._access_tokens.pop(token.token, None)
            self._refresh_tokens.pop(token.token, None)
            self._save_state()

    # --- helpers used by the /login route handlers below ---

    def pending_exists(self, txn: str) -> bool:
        self._prune_pending()
        return txn in self._pending

    def pop_pending(self, txn: str):
        self._prune_pending()
        entry = self._pending.pop(txn, None)
        return None if entry is None else (entry[0], entry[1])

    def restore_pending(self, txn: str, client: OAuthClientInformationFull, params: AuthorizationParams) -> None:
        self._pending[txn] = (client, params, time.time() + PENDING_TXN_TTL_SECONDS)

    def check_password(self, password: str) -> bool:
        return secrets.compare_digest(password, self._shared_password)

    def issue_authorization_code(self, client: OAuthClientInformationFull, params: AuthorizationParams) -> str:
        code = secrets.token_urlsafe(32)
        self._auth_codes[code] = AuthorizationCode(
            code=code,
            scopes=params.scopes or [],
            expires_at=time.time() + AUTH_CODE_TTL_SECONDS,
            client_id=client.client_id,
            code_challenge=params.code_challenge,
            redirect_uri=params.redirect_uri,
            redirect_uri_provided_explicitly=params.redirect_uri_provided_explicitly,
            resource=params.resource,
            subject="trusted-group",
        )
        return code

    def _prune_pending(self) -> None:
        now = time.time()
        expired = [txn for txn, (_, _, exp) in self._pending.items() if exp < now]
        for txn in expired:
            self._pending.pop(txn, None)

    def _mint_token(
        self, client: OAuthClientInformationFull, scopes: list[str], *, subject: str | None
    ) -> OAuthToken:
        access_token = secrets.token_urlsafe(32)
        refresh_token = secrets.token_urlsafe(32)
        now = int(time.time())
        assert client.client_id is not None
        self._access_tokens[access_token] = AccessToken(
            token=access_token,
            client_id=client.client_id,
            scopes=scopes,
            expires_at=now + ACCESS_TOKEN_TTL_SECONDS,
            subject=subject,
        )
        self._refresh_tokens[refresh_token] = RefreshToken(
            token=refresh_token,
            client_id=client.client_id,
            scopes=scopes,
            expires_at=now + REFRESH_TOKEN_TTL_SECONDS,
            subject=subject,
        )
        return OAuthToken(
            access_token=access_token,
            token_type="Bearer",
            expires_in=ACCESS_TOKEN_TTL_SECONDS,
            refresh_token=refresh_token,
            scope=" ".join(scopes) if scopes else None,
        )


# --- /login route handlers, registered onto FastMCP via @mcp.custom_route in asgi.py ---


async def login_get(request: Request, provider: SharedPasswordOAuthProvider) -> Response:
    txn = request.query_params.get("txn", "")
    if not provider.pending_exists(txn):
        return HTMLResponse(
            "<p>This sign-in link expired or is invalid. Go back and try connecting again.</p>",
            status_code=400,
        )
    return HTMLResponse(_login_form_html(txn))


async def login_post(request: Request, provider: SharedPasswordOAuthProvider) -> Response:
    form = await request.form()
    txn = str(form.get("txn", ""))
    password = str(form.get("password", ""))
    pending = provider.pop_pending(txn)
    if pending is None:
        return HTMLResponse(
            "<p>This sign-in link expired or is invalid. Go back and try connecting again.</p>",
            status_code=400,
        )
    client, params = pending
    if not provider.check_password(password):
        provider.restore_pending(txn, client, params)
        return HTMLResponse(_login_form_html(txn, error="Incorrect password."), status_code=401)
    code = provider.issue_authorization_code(client, params)
    redirect_url = construct_redirect_uri(str(params.redirect_uri), code=code, state=params.state)
    return RedirectResponse(url=redirect_url, status_code=302, headers={"Cache-Control": "no-store"})
